# Generated by Django 2.2.5 on 2019-09-13 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CountryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Country name')),
                ('alias', models.CharField(max_length=5, verbose_name='Short alias')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyTypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Currency name')),
                ('alias', models.CharField(max_length=5, verbose_name='Currency alias')),
            ],
        ),
        migrations.CreateModel(
            name='OperationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'refill'), (1, 'transfer')], verbose_name='Transaction type')),
                ('datetime', models.DateTimeField(verbose_name='Operation datetime')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'debit'), (1, 'credit')], verbose_name='Transaction type')),
                ('datetime', models.DateTimeField(verbose_name='Transaction datetime')),
                ('exchange_quote', models.DecimalField(decimal_places=6, help_text='The USD exchange rate on operation moment', max_digits=16, verbose_name='USD exchange rate')),
                ('amount', models.IntegerField(verbose_name='Operations amount')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.AccountModel')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.CurrencyTypeModel')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.OperationModel')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyQuotesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_exchange_rate', models.DecimalField(decimal_places=6, max_digits=16, verbose_name='USD exchange rate')),
                ('currency_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.CurrencyTypeModel')),
            ],
        ),
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='City name')),
                ('alias', models.CharField(max_length=20, verbose_name='Short alias')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.CountryModel')),
            ],
        ),
        migrations.AddField(
            model_name='accountmodel',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.CurrencyTypeModel'),
        ),
        migrations.AddField(
            model_name='accountmodel',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.CityModel'),
        ),
        migrations.AddField(
            model_name='accountmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
