# Generated by Django 2.2.5 on 2019-09-15 11:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyquotesmodel',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of value'),
            preserve_default=False,
        ),
    ]
